# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.kv_items_show200_response_value import KVItemsShow200ResponseValue

class TestKVItemsShow200ResponseValue(unittest.TestCase):
    """KVItemsShow200ResponseValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KVItemsShow200ResponseValue:
        """Test KVItemsShow200ResponseValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KVItemsShow200ResponseValue`
        """
        model = KVItemsShow200ResponseValue()
        if include_optional:
            return KVItemsShow200ResponseValue(
            )
        else:
            return KVItemsShow200ResponseValue(
        )
        """

    def testKVItemsShow200ResponseValue(self):
        """Test KVItemsShow200ResponseValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
