# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.21.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_my_usage200_response import GetMyUsage200Response

class TestGetMyUsage200Response(unittest.TestCase):
    """GetMyUsage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMyUsage200Response:
        """Test GetMyUsage200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMyUsage200Response`
        """
        model = GetMyUsage200Response()
        if include_optional:
            return GetMyUsage200Response(
                user_id = '',
                current_month = '2026-03',
                monthly = quantcdn.models.get_my_usage_200_response_monthly.getMyUsage_200_response_monthly(
                    spend_cents = 56, 
                    request_count = 56, ),
                daily = quantcdn.models.get_my_usage_200_response_daily.getMyUsage_200_response_daily(
                    spend_cents = 56, ),
                quota = quantcdn.models.get_my_usage_200_response_quota.getMyUsage_200_response_quota(
                    monthly_limit = quantcdn.models.get_my_usage_200_response_quota_monthly_limit.getMyUsage_200_response_quota_monthlyLimit(
                        limit_cents = 56, 
                        used_percent = 1.337, 
                        remaining_cents = 56, ), 
                    daily_limit = quantcdn.models.get_my_usage_200_response_quota_daily_limit.getMyUsage_200_response_quota_dailyLimit(
                        limit_cents = 56, 
                        used_percent = 1.337, 
                        remaining_cents = 56, 
                        resets_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
            )
        else:
            return GetMyUsage200Response(
        )
        """

    def testGetMyUsage200Response(self):
        """Test GetMyUsage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
