# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v2_store_item_update_request import V2StoreItemUpdateRequest

class TestV2StoreItemUpdateRequest(unittest.TestCase):
    """V2StoreItemUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2StoreItemUpdateRequest:
        """Test V2StoreItemUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2StoreItemUpdateRequest`
        """
        model = V2StoreItemUpdateRequest()
        if include_optional:
            return V2StoreItemUpdateRequest(
                value = '',
                secret = True
            )
        else:
            return V2StoreItemUpdateRequest(
                value = '',
        )
        """

    def testV2StoreItemUpdateRequest(self):
        """Test V2StoreItemUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
