# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.15.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.upload_file201_response import UploadFile201Response

class TestUploadFile201Response(unittest.TestCase):
    """UploadFile201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadFile201Response:
        """Test UploadFile201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadFile201Response`
        """
        model = UploadFile201Response()
        if include_optional:
            return UploadFile201Response(
                file_id = '',
                s3_uri = '',
                url = '',
                upload_url = '',
                s3_key = '',
                expires_in = 56,
                filename = '',
                content_type = '',
                size = 56,
                metadata = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UploadFile201Response(
        )
        """

    def testUploadFile201Response(self):
        """Test UploadFile201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
