# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.list_ai_tool_names200_response import ListAIToolNames200Response

class TestListAIToolNames200Response(unittest.TestCase):
    """ListAIToolNames200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAIToolNames200Response:
        """Test ListAIToolNames200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAIToolNames200Response`
        """
        model = ListAIToolNames200Response()
        if include_optional:
            return ListAIToolNames200Response(
                tools = ["get_weather","calculate","search_web","generate_image"],
                count = 4
            )
        else:
            return ListAIToolNames200Response(
                tools = ["get_weather","calculate","search_web","generate_image"],
                count = 4,
        )
        """

    def testListAIToolNames200Response(self):
        """Test ListAIToolNames200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
