# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.delete_custom_tool200_response import DeleteCustomTool200Response

class TestDeleteCustomTool200Response(unittest.TestCase):
    """DeleteCustomTool200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteCustomTool200Response:
        """Test DeleteCustomTool200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteCustomTool200Response`
        """
        model = DeleteCustomTool200Response()
        if include_optional:
            return DeleteCustomTool200Response(
                success = True,
                message = 'Custom tool deleted successfully'
            )
        else:
            return DeleteCustomTool200Response(
        )
        """

    def testDeleteCustomTool200Response(self):
        """Test DeleteCustomTool200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
