# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.15.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_skill200_response import GetSkill200Response

class TestGetSkill200Response(unittest.TestCase):
    """GetSkill200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSkill200Response:
        """Test GetSkill200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSkill200Response`
        """
        model = GetSkill200Response()
        if include_optional:
            return GetSkill200Response(
                skill = quantcdn.models.get_skill_200_response_skill.getSkill_200_response_skill(
                    skill_id = '', 
                    name = '', 
                    description = '', 
                    content = '', 
                    trigger_condition = '', 
                    tags = [
                        ''
                        ], 
                    source = quantcdn.models.source.source(), 
                    required_tools = [
                        ''
                        ], 
                    files = quantcdn.models.files.files(), 
                    namespace = '', 
                    disable_model_invocation = True, 
                    allowed_tools = [
                        ''
                        ], 
                    installed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetSkill200Response(
        )
        """

    def testGetSkill200Response(self):
        """Test GetSkill200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
