# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.15.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.upsert_agent_overlay_request import UpsertAgentOverlayRequest

class TestUpsertAgentOverlayRequest(unittest.TestCase):
    """UpsertAgentOverlayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertAgentOverlayRequest:
        """Test UpsertAgentOverlayRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertAgentOverlayRequest`
        """
        model = UpsertAgentOverlayRequest()
        if include_optional:
            return UpsertAgentOverlayRequest(
                model_id = '',
                temperature = 0,
                max_tokens = 1,
                disabled_skills = [
                    ''
                    ],
                additional_skills = [
                    ''
                    ],
                additional_tools = [
                    ''
                    ],
                disabled_tools = [
                    ''
                    ],
                system_prompt_append = '',
                allowed_collections = [
                    ''
                    ],
                guardrail_preset = 'official',
                version = 56
            )
        else:
            return UpsertAgentOverlayRequest(
        )
        """

    def testUpsertAgentOverlayRequest(self):
        """Test UpsertAgentOverlayRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
