# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_ai_session200_response import GetAISession200Response

class TestGetAISession200Response(unittest.TestCase):
    """GetAISession200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAISession200Response:
        """Test GetAISession200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAISession200Response`
        """
        model = GetAISession200Response()
        if include_optional:
            return GetAISession200Response(
                id = '',
                title = '',
                model = '',
                messages = [
                    None
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetAISession200Response(
        )
        """

    def testGetAISession200Response(self):
        """Test GetAISession200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
