# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_environment_logs200_response import GetEnvironmentLogs200Response

class TestGetEnvironmentLogs200Response(unittest.TestCase):
    """GetEnvironmentLogs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEnvironmentLogs200Response:
        """Test GetEnvironmentLogs200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEnvironmentLogs200Response`
        """
        model = GetEnvironmentLogs200Response()
        if include_optional:
            return GetEnvironmentLogs200Response(
                log_events = [
                    quantcdn.models.get_environment_logs_200_response_log_events_inner.getEnvironmentLogs_200_response_logEvents_inner(
                        timestamp = 56, 
                        message = '', )
                    ],
                next_token = ''
            )
        else:
            return GetEnvironmentLogs200Response(
        )
        """

    def testGetEnvironmentLogs200Response(self):
        """Test GetEnvironmentLogs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
