# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.api.ai_agents_api import AIAgentsApi


class TestAIAgentsApi(unittest.TestCase):
    """AIAgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AIAgentsApi()

    def tearDown(self) -> None:
        pass

    def test_chat_with_ai_agent(self) -> None:
        """Test case for chat_with_ai_agent

        Chat with AI Agent
        """
        pass

    def test_create_ai_agent(self) -> None:
        """Test case for create_ai_agent

        Create AI Agent
        """
        pass

    def test_delete_ai_agent(self) -> None:
        """Test case for delete_ai_agent

        Delete Agent
        """
        pass

    def test_get_ai_agent(self) -> None:
        """Test case for get_ai_agent

        Get Agent Details
        """
        pass

    def test_list_ai_agents(self) -> None:
        """Test case for list_ai_agents

        List AI Agents
        """
        pass

    def test_update_ai_agent(self) -> None:
        """Test case for update_ai_agent

        Update Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
