# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.20.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.create_slack_bot201_response import CreateSlackBot201Response

class TestCreateSlackBot201Response(unittest.TestCase):
    """CreateSlackBot201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSlackBot201Response:
        """Test CreateSlackBot201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSlackBot201Response`
        """
        model = CreateSlackBot201Response()
        if include_optional:
            return CreateSlackBot201Response(
                bot = None
            )
        else:
            return CreateSlackBot201Response(
        )
        """

    def testCreateSlackBot201Response(self):
        """Test CreateSlackBot201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
