# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.list_mcp_servers200_response_servers_inner import ListMcpServers200ResponseServersInner

class TestListMcpServers200ResponseServersInner(unittest.TestCase):
    """ListMcpServers200ResponseServersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMcpServers200ResponseServersInner:
        """Test ListMcpServers200ResponseServersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListMcpServers200ResponseServersInner`
        """
        model = ListMcpServers200ResponseServersInner()
        if include_optional:
            return ListMcpServers200ResponseServersInner(
                server_name = '',
                display_name = '',
                url = '',
                enabled = True,
                tool_allowlist = [
                    ''
                    ]
            )
        else:
            return ListMcpServers200ResponseServersInner(
        )
        """

    def testListMcpServers200ResponseServersInner(self):
        """Test ListMcpServers200ResponseServersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
