# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.19.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.oai_chat_completions_request_messages_inner import OaiChatCompletionsRequestMessagesInner

class TestOaiChatCompletionsRequestMessagesInner(unittest.TestCase):
    """OaiChatCompletionsRequestMessagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OaiChatCompletionsRequestMessagesInner:
        """Test OaiChatCompletionsRequestMessagesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OaiChatCompletionsRequestMessagesInner`
        """
        model = OaiChatCompletionsRequestMessagesInner()
        if include_optional:
            return OaiChatCompletionsRequestMessagesInner(
                role = 'system',
                content = ''
            )
        else:
            return OaiChatCompletionsRequestMessagesInner(
        )
        """

    def testOaiChatCompletionsRequestMessagesInner(self):
        """Test OaiChatCompletionsRequestMessagesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
