# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v1_metric_day_stats import V1MetricDayStats

class TestV1MetricDayStats(unittest.TestCase):
    """V1MetricDayStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MetricDayStats:
        """Test V1MetricDayStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MetricDayStats`
        """
        model = V1MetricDayStats()
        if include_optional:
            return V1MetricDayStats(
                total = 56,
                day_total = 56,
                day_series = {
                    'key' : 1.337
                    },
                day_average = 1.337
            )
        else:
            return V1MetricDayStats(
                total = 56,
                day_total = 56,
                day_series = {
                    'key' : 1.337
                    },
                day_average = 1.337,
        )
        """

    def testV1MetricDayStats(self):
        """Test V1MetricDayStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
