# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v2_store import V2Store

class TestV2Store(unittest.TestCase):
    """V2Store unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2Store:
        """Test V2Store
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2Store`
        """
        model = V2Store()
        if include_optional:
            return V2Store(
                id = 'kv-store-123',
                name = 'session-data'
            )
        else:
            return V2Store(
                id = 'kv-store-123',
                name = 'session-data',
        )
        """

    def testV2Store(self):
        """Test V2Store"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
