# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.crawlers_run_request import CrawlersRunRequest

class TestCrawlersRunRequest(unittest.TestCase):
    """CrawlersRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrawlersRunRequest:
        """Test CrawlersRunRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrawlersRunRequest`
        """
        model = CrawlersRunRequest()
        if include_optional:
            return CrawlersRunRequest(
                urls = ["/","/about","/contact"]
            )
        else:
            return CrawlersRunRequest(
        )
        """

    def testCrawlersRunRequest(self):
        """Test CrawlersRunRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
