# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_dependency_graph200_response import GetDependencyGraph200Response

class TestGetDependencyGraph200Response(unittest.TestCase):
    """GetDependencyGraph200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDependencyGraph200Response:
        """Test GetDependencyGraph200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDependencyGraph200Response`
        """
        model = GetDependencyGraph200Response()
        if include_optional:
            return GetDependencyGraph200Response(
                task_list_id = 'world-1',
                task_count = 4,
                roots = [
                    ''
                    ],
                leaves = [
                    ''
                    ],
                graph = None
            )
        else:
            return GetDependencyGraph200Response(
        )
        """

    def testGetDependencyGraph200Response(self):
        """Test GetDependencyGraph200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
