# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.api.orchestration_api import OrchestrationApi


class TestOrchestrationApi(unittest.TestCase):
    """OrchestrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrchestrationApi()

    def tearDown(self) -> None:
        pass

    def test_get_ai_orchestration_status(self) -> None:
        """Test case for get_ai_orchestration_status

        Get Tool Orchestration Status (Async Tool Polling)
        """
        pass


if __name__ == '__main__':
    unittest.main()
