# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.environment_summary import EnvironmentSummary

class TestEnvironmentSummary(unittest.TestCase):
    """EnvironmentSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvironmentSummary:
        """Test EnvironmentSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvironmentSummary`
        """
        model = EnvironmentSummary()
        if include_optional:
            return EnvironmentSummary(
                env_name = 'production',
                status = 'ACTIVE',
                deployment_status = 'COMPLETED',
                running_count = 2,
                desired_count = 2,
                min_capacity = 1,
                max_capacity = 5
            )
        else:
            return EnvironmentSummary(
        )
        """

    def testEnvironmentSummary(self):
        """Test EnvironmentSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
