# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_slack_bot200_response import GetSlackBot200Response

class TestGetSlackBot200Response(unittest.TestCase):
    """GetSlackBot200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSlackBot200Response:
        """Test GetSlackBot200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSlackBot200Response`
        """
        model = GetSlackBot200Response()
        if include_optional:
            return GetSlackBot200Response(
                bot = quantcdn.models.get_slack_bot_200_response_bot.getSlackBot_200_response_bot(
                    bot_id = '', 
                    name = '', 
                    setup_type = 'quant', 
                    status = 'active', 
                    connected = True, 
                    system_prompt = '', 
                    model_id = '', 
                    temperature = 1.337, 
                    max_tokens = 56, 
                    allowed_tools = [
                        ''
                        ], 
                    assigned_skills = [
                        ''
                        ], 
                    allowed_collections = [
                        ''
                        ], 
                    allowed_sub_agents = [
                        ''
                        ], 
                    guardrail_preset = '', 
                    filter_policies = [
                        ''
                        ], 
                    long_context = True, 
                    session_ttl_days = 56, 
                    allowed_channels = [
                        ''
                        ], 
                    allowed_users = [
                        ''
                        ], 
                    denied_users = [
                        ''
                        ], 
                    allow_guests = True, 
                    home_tab_content = '', 
                    agent_access_control = quantcdn.models.agent_access_control.agentAccessControl(), 
                    keywords_enabled = True, 
                    keywords = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetSlackBot200Response(
        )
        """

    def testGetSlackBot200Response(self):
        """Test GetSlackBot200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
