# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v2_rule_serve_static_request import V2RuleServeStaticRequest

class TestV2RuleServeStaticRequest(unittest.TestCase):
    """V2RuleServeStaticRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2RuleServeStaticRequest:
        """Test V2RuleServeStaticRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2RuleServeStaticRequest`
        """
        model = V2RuleServeStaticRequest()
        if include_optional:
            return V2RuleServeStaticRequest(
                domain = [test-domain.com, *.test-domain.com],
                name = 'Test redirect rule',
                uuid = '123e4567-e89b-12d3-a456-426614174000',
                weight = 100,
                disabled = False,
                url = [/old-path/*, /legacy/*],
                country = 'country_is',
                country_is = [US, CA, GB],
                country_is_not = [CN, RU],
                method = 'method_is',
                method_is = [GET, POST],
                method_is_not = [DELETE, PUT],
                ip = 'ip_is',
                ip_is = [192.168.1.0/24, 10.0.0.1],
                ip_is_not = [172.16.0.0/12],
                static_file_path = '/index.html'
            )
        else:
            return V2RuleServeStaticRequest(
                domain = [test-domain.com, *.test-domain.com],
                url = [/old-path/*, /legacy/*],
                static_file_path = '/index.html',
        )
        """

    def testV2RuleServeStaticRequest(self):
        """Test V2RuleServeStaticRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
