# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.13.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.update_task200_response import UpdateTask200Response

class TestUpdateTask200Response(unittest.TestCase):
    """UpdateTask200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTask200Response:
        """Test UpdateTask200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTask200Response`
        """
        model = UpdateTask200Response()
        if include_optional:
            return UpdateTask200Response(
                task_id = '',
                status = '',
                updated_at = 56
            )
        else:
            return UpdateTask200Response(
        )
        """

    def testUpdateTask200Response(self):
        """Test UpdateTask200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
