# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.17.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_governance_config200_response_spend_limits import GetGovernanceConfig200ResponseSpendLimits

class TestGetGovernanceConfig200ResponseSpendLimits(unittest.TestCase):
    """GetGovernanceConfig200ResponseSpendLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGovernanceConfig200ResponseSpendLimits:
        """Test GetGovernanceConfig200ResponseSpendLimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGovernanceConfig200ResponseSpendLimits`
        """
        model = GetGovernanceConfig200ResponseSpendLimits()
        if include_optional:
            return GetGovernanceConfig200ResponseSpendLimits(
                monthly_budget_cents = 56,
                daily_budget_cents = 56,
                per_user_monthly_budget_cents = 56,
                per_user_daily_budget_cents = 56,
                warning_threshold_percent = 56
            )
        else:
            return GetGovernanceConfig200ResponseSpendLimits(
        )
        """

    def testGetGovernanceConfig200ResponseSpendLimits(self):
        """Test GetGovernanceConfig200ResponseSpendLimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
