# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.image_generation_request import ImageGenerationRequest

class TestImageGenerationRequest(unittest.TestCase):
    """ImageGenerationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageGenerationRequest:
        """Test ImageGenerationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageGenerationRequest`
        """
        model = ImageGenerationRequest()
        if include_optional:
            return ImageGenerationRequest(
                model_id = 'amazon.nova-canvas-v1:0',
                task_type = 'TEXT_IMAGE',
                text_to_image_params = quantcdn.models.image_generation_request_text_to_image_params.imageGeneration_request_textToImageParams(
                    text = '0', 
                    negative_text = '0', 
                    style = '3D_ANIMATED_FAMILY_FILM', 
                    condition_image = 'YQ==', 
                    control_mode = 'CANNY_EDGE', 
                    control_strength = 0, ),
                color_guided_generation_params = quantcdn.models.image_generation_request_color_guided_generation_params.imageGeneration_request_colorGuidedGenerationParams(
                    colors = [
                        '#62ECB0'
                        ], 
                    reference_image = 'YQ==', 
                    text = '0', 
                    negative_text = '0', ),
                image_variation_params = quantcdn.models.image_generation_request_image_variation_params.imageGeneration_request_imageVariationParams(
                    images = [
                        'YQ=='
                        ], 
                    similarity_strength = 0.2, 
                    text = '0', 
                    negative_text = '0', ),
                in_painting_params = quantcdn.models.image_generation_request_in_painting_params.imageGeneration_request_inPaintingParams(
                    image = 'YQ==', 
                    mask_image = 'YQ==', 
                    mask_prompt = '', 
                    text = '0', 
                    negative_text = '', ),
                out_painting_params = quantcdn.models.image_generation_request_out_painting_params.imageGeneration_request_outPaintingParams(
                    image = 'YQ==', 
                    mask_image = 'YQ==', 
                    mask_prompt = '', 
                    out_painting_mode = 'DEFAULT', 
                    text = '', 
                    negative_text = '', ),
                background_removal_params = quantcdn.models.image_generation_request_background_removal_params.imageGeneration_request_backgroundRemovalParams(
                    image = 'YQ==', ),
                virtual_try_on_params = None,
                image_generation_config = quantcdn.models.image_generation_request_image_generation_config.imageGeneration_request_imageGenerationConfig(
                    width = 1024, 
                    height = 1024, 
                    quality = 'standard', 
                    cfg_scale = 1.1, 
                    seed = 0, 
                    number_of_images = 1, ),
                region = 'us-east-1'
            )
        else:
            return ImageGenerationRequest(
                task_type = 'TEXT_IMAGE',
        )
        """

    def testImageGenerationRequest(self):
        """Test ImageGenerationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
