# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.chat_with_ai_agent200_response import ChatWithAIAgent200Response

class TestChatWithAIAgent200Response(unittest.TestCase):
    """ChatWithAIAgent200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatWithAIAgent200Response:
        """Test ChatWithAIAgent200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatWithAIAgent200Response`
        """
        model = ChatWithAIAgent200Response()
        if include_optional:
            return ChatWithAIAgent200Response(
                session_id = '',
                response = quantcdn.models.chat_with_ai_agent_200_response_response.chatWithAIAgent_200_response_response(
                    text = '', 
                    stop_reason = '', 
                    usage = quantcdn.models.chat_with_ai_agent_200_response_response_usage.chatWithAIAgent_200_response_response_usage(
                        input_tokens = 56, 
                        output_tokens = 56, ), 
                    tool_results = [
                        None
                        ], )
            )
        else:
            return ChatWithAIAgent200Response(
        )
        """

    def testChatWithAIAgent200Response(self):
        """Test ChatWithAIAgent200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
