# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.list_backups200_response_backups_inner import ListBackups200ResponseBackupsInner

class TestListBackups200ResponseBackupsInner(unittest.TestCase):
    """ListBackups200ResponseBackupsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBackups200ResponseBackupsInner:
        """Test ListBackups200ResponseBackupsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBackups200ResponseBackupsInner`
        """
        model = ListBackups200ResponseBackupsInner()
        if include_optional:
            return ListBackups200ResponseBackupsInner(
                backup_id = 'quant-gov-dashboard-staging-2025-09-19T21-50-27-145Z',
                status = 'completed',
                type = 'logical',
                engine = 'mysql',
                description = 'Manual backup',
                created_at = '2025-09-19T21:50:27.317Z',
                updated_at = '2025-09-19T21:51:09Z',
                task_arn = 'arn:aws:ecs:ap-southeast-4:056500205767:task/au-prd-quant-cloud-cluster/305a68f04bf641f887a87b74d67fa57e',
                s3_key = 'database-backups/quant-gov/dashboard/staging/quant-gov-dashboard-staging-2025-09-19T21-50-27-145Z.sql.gz',
                bucket_name = 'au-prd-manual-backups',
                size = 1945663,
                size_formatted = '1.86 MB',
                file_exists = True
            )
        else:
            return ListBackups200ResponseBackupsInner(
        )
        """

    def testListBackups200ResponseBackupsInner(self):
        """Test ListBackups200ResponseBackupsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
