# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v1_get_metrics_response import V1GetMetricsResponse

class TestV1GetMetricsResponse(unittest.TestCase):
    """V1GetMetricsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GetMetricsResponse:
        """Test V1GetMetricsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GetMetricsResponse`
        """
        model = V1GetMetricsResponse()
        if include_optional:
            return V1GetMetricsResponse(
                success = True,
                data = None
            )
        else:
            return V1GetMetricsResponse(
                success = True,
                data = None,
        )
        """

    def testV1GetMetricsResponse(self):
        """Test V1GetMetricsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
