# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.24.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v2_rule_error_page_request import V2RuleErrorPageRequest

class TestV2RuleErrorPageRequest(unittest.TestCase):
    """V2RuleErrorPageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2RuleErrorPageRequest:
        """Test V2RuleErrorPageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2RuleErrorPageRequest`
        """
        model = V2RuleErrorPageRequest()
        if include_optional:
            return V2RuleErrorPageRequest(
                domain = [test-domain.com, *.test-domain.com],
                name = 'Test redirect rule',
                uuid = '123e4567-e89b-12d3-a456-426614174000',
                weight = 100,
                disabled = False,
                url = [/old-path/*, /legacy/*],
                country = 'country_is',
                country_is = [US, CA, GB],
                country_is_not = [CN, RU],
                method = 'method_is',
                method_is = [GET, POST],
                method_is_not = [DELETE, PUT],
                ip = 'ip_is',
                ip_is = [192.168.1.0/24, 10.0.0.1],
                ip_is_not = [172.16.0.0/12],
                asn = 'any',
                asn_is = [15169, 8075],
                asn_is_not = [13335],
                error_page_path = '/fr/_quant404',
                status_codes = ["404"]
            )
        else:
            return V2RuleErrorPageRequest(
                domain = [test-domain.com, *.test-domain.com],
                url = [/old-path/*, /legacy/*],
                error_page_path = '/fr/_quant404',
                status_codes = ["404"],
        )
        """

    def testV2RuleErrorPageRequest(self):
        """Test V2RuleErrorPageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
