# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.v1_url_meta_request import V1UrlMetaRequest

class TestV1UrlMetaRequest(unittest.TestCase):
    """V1UrlMetaRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1UrlMetaRequest:
        """Test V1UrlMetaRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1UrlMetaRequest`
        """
        model = V1UrlMetaRequest()
        if include_optional:
            return V1UrlMetaRequest(
                quant_url = ["/home","/css/styles.css","/contact-us"]
            )
        else:
            return V1UrlMetaRequest(
                quant_url = ["/home","/css/styles.css","/contact-us"],
        )
        """

    def testV1UrlMetaRequest(self):
        """Test V1UrlMetaRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
