# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_ssh_access_credentials200_response import GetSshAccessCredentials200Response

class TestGetSshAccessCredentials200Response(unittest.TestCase):
    """GetSshAccessCredentials200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSshAccessCredentials200Response:
        """Test GetSshAccessCredentials200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSshAccessCredentials200Response`
        """
        model = GetSshAccessCredentials200Response()
        if include_optional:
            return GetSshAccessCredentials200Response(
                success = True,
                credentials = quantcdn.models.get_ssh_access_credentials_200_response_credentials.getSshAccessCredentials_200_response_credentials(
                    access_key_id = '', 
                    secret_access_key = '', 
                    session_token = '', 
                    expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                cluster_name = '',
                task_arn = '',
                task_id = '',
                container_names = [
                    ''
                    ],
                region = '',
                expires_in = 56,
                organization_scope = ''
            )
        else:
            return GetSshAccessCredentials200Response(
        )
        """

    def testGetSshAccessCredentials200Response(self):
        """Test GetSshAccessCredentials200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
