# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.21.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.scaling_policy_list_response import ScalingPolicyListResponse

class TestScalingPolicyListResponse(unittest.TestCase):
    """ScalingPolicyListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScalingPolicyListResponse:
        """Test ScalingPolicyListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScalingPolicyListResponse`
        """
        model = ScalingPolicyListResponse()
        if include_optional:
            return ScalingPolicyListResponse(
                policies = [
                    quantcdn.models.get_scaling_policy_response.GetScalingPolicyResponse(
                        metric = 'CPUUtilization', 
                        target_value = 1.337, 
                        scale_in_cooldown_seconds = 56, 
                        scale_out_cooldown_seconds = 56, 
                        policy_name = '', 
                        resource_label = '', )
                    ]
            )
        else:
            return ScalingPolicyListResponse(
        )
        """

    def testScalingPolicyListResponse(self):
        """Test ScalingPolicyListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
