# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_ai_orchestration_status200_response_tools_inner import GetAIOrchestrationStatus200ResponseToolsInner

class TestGetAIOrchestrationStatus200ResponseToolsInner(unittest.TestCase):
    """GetAIOrchestrationStatus200ResponseToolsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAIOrchestrationStatus200ResponseToolsInner:
        """Test GetAIOrchestrationStatus200ResponseToolsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAIOrchestrationStatus200ResponseToolsInner`
        """
        model = GetAIOrchestrationStatus200ResponseToolsInner()
        if include_optional:
            return GetAIOrchestrationStatus200ResponseToolsInner(
                execution_id = 'exec_abc123def456',
                tool_name = 'generate_image',
                status = 'complete',
                result = None,
                error = ''
            )
        else:
            return GetAIOrchestrationStatus200ResponseToolsInner(
        )
        """

    def testGetAIOrchestrationStatus200ResponseToolsInner(self):
        """Test GetAIOrchestrationStatus200ResponseToolsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
