# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.15.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.api.cdn_metrics_api import CDNMetricsApi


class TestCDNMetricsApi(unittest.TestCase):
    """CDNMetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CDNMetricsApi()

    def tearDown(self) -> None:
        pass

    def test_get_daily_metrics(self) -> None:
        """Test case for get_daily_metrics

        Get daily metrics
        """
        pass

    def test_get_hourly_metrics(self) -> None:
        """Test case for get_hourly_metrics

        Get hourly metrics
        """
        pass

    def test_get_monthly_metrics(self) -> None:
        """Test case for get_monthly_metrics

        Get monthly metrics
        """
        pass


if __name__ == '__main__':
    unittest.main()
