# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.update_environment_variable_request import UpdateEnvironmentVariableRequest

class TestUpdateEnvironmentVariableRequest(unittest.TestCase):
    """UpdateEnvironmentVariableRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateEnvironmentVariableRequest:
        """Test UpdateEnvironmentVariableRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateEnvironmentVariableRequest`
        """
        model = UpdateEnvironmentVariableRequest()
        if include_optional:
            return UpdateEnvironmentVariableRequest(
                value = ''
            )
        else:
            return UpdateEnvironmentVariableRequest(
        )
        """

    def testUpdateEnvironmentVariableRequest(self):
        """Test UpdateEnvironmentVariableRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
