# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.15.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.delete_task409_response import DeleteTask409Response

class TestDeleteTask409Response(unittest.TestCase):
    """DeleteTask409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteTask409Response:
        """Test DeleteTask409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteTask409Response`
        """
        model = DeleteTask409Response()
        if include_optional:
            return DeleteTask409Response(
                error = 'TASK_HAS_DEPENDENTS',
                message = 'Cannot delete task with 3 dependent task(s). Use cascade=true to delete all.',
                dependent_task_ids = [
                    ''
                    ]
            )
        else:
            return DeleteTask409Response(
        )
        """

    def testDeleteTask409Response(self):
        """Test DeleteTask409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
