# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.get_agent_overlay200_response_overlay import GetAgentOverlay200ResponseOverlay

class TestGetAgentOverlay200ResponseOverlay(unittest.TestCase):
    """GetAgentOverlay200ResponseOverlay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAgentOverlay200ResponseOverlay:
        """Test GetAgentOverlay200ResponseOverlay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAgentOverlay200ResponseOverlay`
        """
        model = GetAgentOverlay200ResponseOverlay()
        if include_optional:
            return GetAgentOverlay200ResponseOverlay(
                model_id = '',
                temperature = 1.337,
                max_tokens = 56,
                disabled_skills = [
                    ''
                    ],
                additional_skills = [
                    ''
                    ],
                additional_tools = [
                    ''
                    ],
                disabled_tools = [
                    ''
                    ],
                system_prompt_append = '',
                allowed_collections = [
                    ''
                    ],
                guardrail_preset = '',
                version = 56
            )
        else:
            return GetAgentOverlay200ResponseOverlay(
        )
        """

    def testGetAgentOverlay200ResponseOverlay(self):
        """Test GetAgentOverlay200ResponseOverlay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
