# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from quantcdn.models.delete_ai_agent200_response import DeleteAIAgent200Response

class TestDeleteAIAgent200Response(unittest.TestCase):
    """DeleteAIAgent200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteAIAgent200Response:
        """Test DeleteAIAgent200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteAIAgent200Response`
        """
        model = DeleteAIAgent200Response()
        if include_optional:
            return DeleteAIAgent200Response(
                success = True,
                message = 'Agent deleted successfully'
            )
        else:
            return DeleteAIAgent200Response(
        )
        """

    def testDeleteAIAgent200Response(self):
        """Test DeleteAIAgent200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
