# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from quantcdn.models.container_depends_on_inner import ContainerDependsOnInner
from quantcdn.models.container_environment_inner import ContainerEnvironmentInner
from quantcdn.models.container_health_check import ContainerHealthCheck
from quantcdn.models.container_image_reference import ContainerImageReference
from quantcdn.models.container_mount_points_inner import ContainerMountPointsInner
from quantcdn.models.container_origin_protection_config import ContainerOriginProtectionConfig
from quantcdn.models.container_secrets_inner import ContainerSecretsInner
from typing import Optional, Set
from typing_extensions import Self

class Container(BaseModel):
    """
    Container
    """ # noqa: E501
    name: Annotated[str, Field(strict=True)] = Field(description="Name of the container")
    image_reference: ContainerImageReference = Field(alias="imageReference")
    cpu: Optional[StrictInt] = Field(default=None, description="Container-level CPU units")
    memory: Optional[StrictInt] = Field(default=None, description="Container-level memory hard limit (MiB)")
    memory_reservation: Optional[StrictInt] = Field(default=None, description="Container-level memory soft limit (MiB)", alias="memoryReservation")
    exposed_ports: Optional[List[StrictInt]] = Field(default=None, description="List of container ports to expose", alias="exposedPorts")
    mount_points: Optional[List[ContainerMountPointsInner]] = Field(default=None, alias="mountPoints")
    environment: Optional[List[ContainerEnvironmentInner]] = Field(default=None, description="Environment variables specific to this container")
    secrets: Optional[List[ContainerSecretsInner]] = Field(default=None, description="Secrets mapped to environment variables")
    health_check: Optional[ContainerHealthCheck] = Field(default=None, alias="healthCheck")
    depends_on: Optional[List[ContainerDependsOnInner]] = Field(default=None, description="Container startup dependencies", alias="dependsOn")
    command: Optional[List[StrictStr]] = None
    entry_point: Optional[List[StrictStr]] = Field(default=None, alias="entryPoint")
    working_directory: Optional[StrictStr] = Field(default=None, alias="workingDirectory")
    essential: Optional[StrictBool] = True
    readonly_root_filesystem: Optional[StrictBool] = Field(default=False, alias="readonlyRootFilesystem")
    user: Optional[StrictStr] = None
    origin_protection: Optional[StrictBool] = Field(default=False, description="Enable origin protection for all exposed ports on this container. Use originProtectionConfig for advanced options like IP allow lists.", alias="originProtection")
    origin_protection_config: Optional[ContainerOriginProtectionConfig] = Field(default=None, alias="originProtectionConfig")
    __properties: ClassVar[List[str]] = ["name", "imageReference", "cpu", "memory", "memoryReservation", "exposedPorts", "mountPoints", "environment", "secrets", "healthCheck", "dependsOn", "command", "entryPoint", "workingDirectory", "essential", "readonlyRootFilesystem", "user", "originProtection", "originProtectionConfig"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Container from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image_reference
        if self.image_reference:
            _dict['imageReference'] = self.image_reference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in mount_points (list)
        _items = []
        if self.mount_points:
            for _item_mount_points in self.mount_points:
                if _item_mount_points:
                    _items.append(_item_mount_points.to_dict())
            _dict['mountPoints'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in environment (list)
        _items = []
        if self.environment:
            for _item_environment in self.environment:
                if _item_environment:
                    _items.append(_item_environment.to_dict())
            _dict['environment'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in secrets (list)
        _items = []
        if self.secrets:
            for _item_secrets in self.secrets:
                if _item_secrets:
                    _items.append(_item_secrets.to_dict())
            _dict['secrets'] = _items
        # override the default output from pydantic by calling `to_dict()` of health_check
        if self.health_check:
            _dict['healthCheck'] = self.health_check.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in depends_on (list)
        _items = []
        if self.depends_on:
            for _item_depends_on in self.depends_on:
                if _item_depends_on:
                    _items.append(_item_depends_on.to_dict())
            _dict['dependsOn'] = _items
        # override the default output from pydantic by calling `to_dict()` of origin_protection_config
        if self.origin_protection_config:
            _dict['originProtectionConfig'] = self.origin_protection_config.to_dict()
        # set to None if cpu (nullable) is None
        # and model_fields_set contains the field
        if self.cpu is None and "cpu" in self.model_fields_set:
            _dict['cpu'] = None

        # set to None if memory (nullable) is None
        # and model_fields_set contains the field
        if self.memory is None and "memory" in self.model_fields_set:
            _dict['memory'] = None

        # set to None if memory_reservation (nullable) is None
        # and model_fields_set contains the field
        if self.memory_reservation is None and "memory_reservation" in self.model_fields_set:
            _dict['memoryReservation'] = None

        # set to None if exposed_ports (nullable) is None
        # and model_fields_set contains the field
        if self.exposed_ports is None and "exposed_ports" in self.model_fields_set:
            _dict['exposedPorts'] = None

        # set to None if mount_points (nullable) is None
        # and model_fields_set contains the field
        if self.mount_points is None and "mount_points" in self.model_fields_set:
            _dict['mountPoints'] = None

        # set to None if environment (nullable) is None
        # and model_fields_set contains the field
        if self.environment is None and "environment" in self.model_fields_set:
            _dict['environment'] = None

        # set to None if secrets (nullable) is None
        # and model_fields_set contains the field
        if self.secrets is None and "secrets" in self.model_fields_set:
            _dict['secrets'] = None

        # set to None if health_check (nullable) is None
        # and model_fields_set contains the field
        if self.health_check is None and "health_check" in self.model_fields_set:
            _dict['healthCheck'] = None

        # set to None if depends_on (nullable) is None
        # and model_fields_set contains the field
        if self.depends_on is None and "depends_on" in self.model_fields_set:
            _dict['dependsOn'] = None

        # set to None if command (nullable) is None
        # and model_fields_set contains the field
        if self.command is None and "command" in self.model_fields_set:
            _dict['command'] = None

        # set to None if entry_point (nullable) is None
        # and model_fields_set contains the field
        if self.entry_point is None and "entry_point" in self.model_fields_set:
            _dict['entryPoint'] = None

        # set to None if working_directory (nullable) is None
        # and model_fields_set contains the field
        if self.working_directory is None and "working_directory" in self.model_fields_set:
            _dict['workingDirectory'] = None

        # set to None if essential (nullable) is None
        # and model_fields_set contains the field
        if self.essential is None and "essential" in self.model_fields_set:
            _dict['essential'] = None

        # set to None if readonly_root_filesystem (nullable) is None
        # and model_fields_set contains the field
        if self.readonly_root_filesystem is None and "readonly_root_filesystem" in self.model_fields_set:
            _dict['readonlyRootFilesystem'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if origin_protection (nullable) is None
        # and model_fields_set contains the field
        if self.origin_protection is None and "origin_protection" in self.model_fields_set:
            _dict['originProtection'] = None

        # set to None if origin_protection_config (nullable) is None
        # and model_fields_set contains the field
        if self.origin_protection_config is None and "origin_protection_config" in self.model_fields_set:
            _dict['originProtectionConfig'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Container from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "imageReference": ContainerImageReference.from_dict(obj["imageReference"]) if obj.get("imageReference") is not None else None,
            "cpu": obj.get("cpu"),
            "memory": obj.get("memory"),
            "memoryReservation": obj.get("memoryReservation"),
            "exposedPorts": obj.get("exposedPorts"),
            "mountPoints": [ContainerMountPointsInner.from_dict(_item) for _item in obj["mountPoints"]] if obj.get("mountPoints") is not None else None,
            "environment": [ContainerEnvironmentInner.from_dict(_item) for _item in obj["environment"]] if obj.get("environment") is not None else None,
            "secrets": [ContainerSecretsInner.from_dict(_item) for _item in obj["secrets"]] if obj.get("secrets") is not None else None,
            "healthCheck": ContainerHealthCheck.from_dict(obj["healthCheck"]) if obj.get("healthCheck") is not None else None,
            "dependsOn": [ContainerDependsOnInner.from_dict(_item) for _item in obj["dependsOn"]] if obj.get("dependsOn") is not None else None,
            "command": obj.get("command"),
            "entryPoint": obj.get("entryPoint"),
            "workingDirectory": obj.get("workingDirectory"),
            "essential": obj.get("essential") if obj.get("essential") is not None else True,
            "readonlyRootFilesystem": obj.get("readonlyRootFilesystem") if obj.get("readonlyRootFilesystem") is not None else False,
            "user": obj.get("user"),
            "originProtection": obj.get("originProtection") if obj.get("originProtection") is not None else False,
            "originProtectionConfig": ContainerOriginProtectionConfig.from_dict(obj["originProtectionConfig"]) if obj.get("originProtectionConfig") is not None else None
        })
        return _obj


