# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.15.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from quantcdn.models.create_orchestration_request_input_source import CreateOrchestrationRequestInputSource
from quantcdn.models.create_orchestration_request_stop_condition import CreateOrchestrationRequestStopCondition
from typing import Optional, Set
from typing_extensions import Self

class CreateOrchestrationRequest(BaseModel):
    """
    CreateOrchestrationRequest
    """ # noqa: E501
    name: StrictStr = Field(description="Orchestration name")
    description: Optional[StrictStr] = Field(default=None, description="Optional description")
    agent_id: Optional[StrictStr] = Field(default=None, description="Agent to process items", alias="agentId")
    tool_id: Optional[StrictStr] = Field(default=None, description="Tool to execute for items", alias="toolId")
    workflow_id: Optional[StrictStr] = Field(default=None, description="Workflow to run for items", alias="workflowId")
    input_source: CreateOrchestrationRequestInputSource = Field(alias="inputSource")
    batch_size: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=10, description="Items per batch", alias="batchSize")
    concurrency: Optional[Annotated[int, Field(le=10, strict=True, ge=1)]] = Field(default=1, description="Concurrent items within a batch")
    stop_condition: Optional[CreateOrchestrationRequestStopCondition] = Field(default=None, alias="stopCondition")
    assigned_skills: Optional[List[StrictStr]] = Field(default=None, description="Skill IDs to assign", alias="assignedSkills")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Optional context merged into each item before processing (e.g. shared credentials or endpoints)")
    auto_start: Optional[StrictBool] = Field(default=True, description="Whether to start immediately", alias="autoStart")
    __properties: ClassVar[List[str]] = ["name", "description", "agentId", "toolId", "workflowId", "inputSource", "batchSize", "concurrency", "stopCondition", "assignedSkills", "context", "autoStart"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrchestrationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_source
        if self.input_source:
            _dict['inputSource'] = self.input_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stop_condition
        if self.stop_condition:
            _dict['stopCondition'] = self.stop_condition.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agentId'] = None

        # set to None if tool_id (nullable) is None
        # and model_fields_set contains the field
        if self.tool_id is None and "tool_id" in self.model_fields_set:
            _dict['toolId'] = None

        # set to None if workflow_id (nullable) is None
        # and model_fields_set contains the field
        if self.workflow_id is None and "workflow_id" in self.model_fields_set:
            _dict['workflowId'] = None

        # set to None if context (nullable) is None
        # and model_fields_set contains the field
        if self.context is None and "context" in self.model_fields_set:
            _dict['context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrchestrationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "agentId": obj.get("agentId"),
            "toolId": obj.get("toolId"),
            "workflowId": obj.get("workflowId"),
            "inputSource": CreateOrchestrationRequestInputSource.from_dict(obj["inputSource"]) if obj.get("inputSource") is not None else None,
            "batchSize": obj.get("batchSize") if obj.get("batchSize") is not None else 10,
            "concurrency": obj.get("concurrency") if obj.get("concurrency") is not None else 1,
            "stopCondition": CreateOrchestrationRequestStopCondition.from_dict(obj["stopCondition"]) if obj.get("stopCondition") is not None else None,
            "assignedSkills": obj.get("assignedSkills"),
            "context": obj.get("context"),
            "autoStart": obj.get("autoStart") if obj.get("autoStart") is not None else True
        })
        return _obj


