# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.19.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from quantcdn.models.get_governance_config200_response_spend_limits_interface_limits_value import GetGovernanceConfig200ResponseSpendLimitsInterfaceLimitsValue
from quantcdn.models.get_governance_config200_response_spend_limits_user_overrides_value import GetGovernanceConfig200ResponseSpendLimitsUserOverridesValue
from typing import Optional, Set
from typing_extensions import Self

class GetGovernanceConfig200ResponseSpendLimits(BaseModel):
    """
    GetGovernanceConfig200ResponseSpendLimits
    """ # noqa: E501
    monthly_budget_cents: Optional[StrictInt] = Field(default=None, alias="monthlyBudgetCents")
    daily_budget_cents: Optional[StrictInt] = Field(default=None, alias="dailyBudgetCents")
    per_user_monthly_budget_cents: Optional[StrictInt] = Field(default=None, alias="perUserMonthlyBudgetCents")
    per_user_daily_budget_cents: Optional[StrictInt] = Field(default=None, alias="perUserDailyBudgetCents")
    warning_threshold_percent: Optional[StrictInt] = Field(default=None, alias="warningThresholdPercent")
    interface_limits: Optional[Dict[str, GetGovernanceConfig200ResponseSpendLimitsInterfaceLimitsValue]] = Field(default=None, description="Aggregate spend caps per interface label (slack, autonomous, api-gateway, streaming, websocket). Keys are interface labels.", alias="interfaceLimits")
    user_overrides: Optional[Dict[str, GetGovernanceConfig200ResponseSpendLimitsUserOverridesValue]] = Field(default=None, description="Per-user budget overrides keyed by userId (numeric portal id, slack-<id>, or system:code-agent). Replaces the flat per-user budget for that user; unlimited=true exempts them.", alias="userOverrides")
    per_token_monthly_budget_cents: Optional[StrictInt] = Field(default=None, description="Flat monthly cap in cents applied to every API token without a named override", alias="perTokenMonthlyBudgetCents")
    per_token_daily_budget_cents: Optional[StrictInt] = Field(default=None, description="Flat daily cap in cents applied to every API token without a named override", alias="perTokenDailyBudgetCents")
    token_overrides: Optional[Dict[str, GetGovernanceConfig200ResponseSpendLimitsUserOverridesValue]] = Field(default=None, description="Per-token budget overrides keyed by API token id. Replaces the flat per-token budget for that token; unlimited=true exempts it.", alias="tokenOverrides")
    __properties: ClassVar[List[str]] = ["monthlyBudgetCents", "dailyBudgetCents", "perUserMonthlyBudgetCents", "perUserDailyBudgetCents", "warningThresholdPercent", "interfaceLimits", "userOverrides", "perTokenMonthlyBudgetCents", "perTokenDailyBudgetCents", "tokenOverrides"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGovernanceConfig200ResponseSpendLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in interface_limits (dict)
        _field_dict = {}
        if self.interface_limits:
            for _key_interface_limits in self.interface_limits:
                if self.interface_limits[_key_interface_limits]:
                    _field_dict[_key_interface_limits] = self.interface_limits[_key_interface_limits].to_dict()
            _dict['interfaceLimits'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in user_overrides (dict)
        _field_dict = {}
        if self.user_overrides:
            for _key_user_overrides in self.user_overrides:
                if self.user_overrides[_key_user_overrides]:
                    _field_dict[_key_user_overrides] = self.user_overrides[_key_user_overrides].to_dict()
            _dict['userOverrides'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in token_overrides (dict)
        _field_dict = {}
        if self.token_overrides:
            for _key_token_overrides in self.token_overrides:
                if self.token_overrides[_key_token_overrides]:
                    _field_dict[_key_token_overrides] = self.token_overrides[_key_token_overrides].to_dict()
            _dict['tokenOverrides'] = _field_dict
        # set to None if monthly_budget_cents (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_budget_cents is None and "monthly_budget_cents" in self.model_fields_set:
            _dict['monthlyBudgetCents'] = None

        # set to None if daily_budget_cents (nullable) is None
        # and model_fields_set contains the field
        if self.daily_budget_cents is None and "daily_budget_cents" in self.model_fields_set:
            _dict['dailyBudgetCents'] = None

        # set to None if per_user_monthly_budget_cents (nullable) is None
        # and model_fields_set contains the field
        if self.per_user_monthly_budget_cents is None and "per_user_monthly_budget_cents" in self.model_fields_set:
            _dict['perUserMonthlyBudgetCents'] = None

        # set to None if per_user_daily_budget_cents (nullable) is None
        # and model_fields_set contains the field
        if self.per_user_daily_budget_cents is None and "per_user_daily_budget_cents" in self.model_fields_set:
            _dict['perUserDailyBudgetCents'] = None

        # set to None if warning_threshold_percent (nullable) is None
        # and model_fields_set contains the field
        if self.warning_threshold_percent is None and "warning_threshold_percent" in self.model_fields_set:
            _dict['warningThresholdPercent'] = None

        # set to None if per_token_monthly_budget_cents (nullable) is None
        # and model_fields_set contains the field
        if self.per_token_monthly_budget_cents is None and "per_token_monthly_budget_cents" in self.model_fields_set:
            _dict['perTokenMonthlyBudgetCents'] = None

        # set to None if per_token_daily_budget_cents (nullable) is None
        # and model_fields_set contains the field
        if self.per_token_daily_budget_cents is None and "per_token_daily_budget_cents" in self.model_fields_set:
            _dict['perTokenDailyBudgetCents'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGovernanceConfig200ResponseSpendLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "monthlyBudgetCents": obj.get("monthlyBudgetCents"),
            "dailyBudgetCents": obj.get("dailyBudgetCents"),
            "perUserMonthlyBudgetCents": obj.get("perUserMonthlyBudgetCents"),
            "perUserDailyBudgetCents": obj.get("perUserDailyBudgetCents"),
            "warningThresholdPercent": obj.get("warningThresholdPercent"),
            "interfaceLimits": dict(
                (_k, GetGovernanceConfig200ResponseSpendLimitsInterfaceLimitsValue.from_dict(_v))
                for _k, _v in obj["interfaceLimits"].items()
            )
            if obj.get("interfaceLimits") is not None
            else None,
            "userOverrides": dict(
                (_k, GetGovernanceConfig200ResponseSpendLimitsUserOverridesValue.from_dict(_v))
                for _k, _v in obj["userOverrides"].items()
            )
            if obj.get("userOverrides") is not None
            else None,
            "perTokenMonthlyBudgetCents": obj.get("perTokenMonthlyBudgetCents"),
            "perTokenDailyBudgetCents": obj.get("perTokenDailyBudgetCents"),
            "tokenOverrides": dict(
                (_k, GetGovernanceConfig200ResponseSpendLimitsUserOverridesValue.from_dict(_v))
                for _k, _v in obj["tokenOverrides"].items()
            )
            if obj.get("tokenOverrides") is not None
            else None
        })
        return _obj


