# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.20.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from quantcdn.models.get_governance_config200_response_spend_limits import GetGovernanceConfig200ResponseSpendLimits
from typing import Optional, Set
from typing_extensions import Self

class GetGovernanceConfig200Response(BaseModel):
    """
    GetGovernanceConfig200Response
    """ # noqa: E501
    org_id: Optional[StrictStr] = Field(default=None, alias="orgId")
    ai_enabled: Optional[StrictBool] = Field(default=None, alias="aiEnabled")
    model_policy: Optional[StrictStr] = Field(default=None, alias="modelPolicy")
    model_list: Optional[List[StrictStr]] = Field(default=None, alias="modelList")
    mandatory_guardrail_preset: Optional[StrictStr] = Field(default=None, alias="mandatoryGuardrailPreset")
    mandatory_filter_policies: Optional[List[StrictStr]] = Field(default=None, alias="mandatoryFilterPolicies")
    spend_limits: Optional[GetGovernanceConfig200ResponseSpendLimits] = Field(default=None, alias="spendLimits")
    version: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["orgId", "aiEnabled", "modelPolicy", "modelList", "mandatoryGuardrailPreset", "mandatoryFilterPolicies", "spendLimits", "version"]

    @field_validator('model_policy')
    def model_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unrestricted', 'allowlist', 'blocklist']):
            raise ValueError("must be one of enum values ('unrestricted', 'allowlist', 'blocklist')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGovernanceConfig200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of spend_limits
        if self.spend_limits:
            _dict['spendLimits'] = self.spend_limits.to_dict()
        # set to None if mandatory_guardrail_preset (nullable) is None
        # and model_fields_set contains the field
        if self.mandatory_guardrail_preset is None and "mandatory_guardrail_preset" in self.model_fields_set:
            _dict['mandatoryGuardrailPreset'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGovernanceConfig200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orgId": obj.get("orgId"),
            "aiEnabled": obj.get("aiEnabled"),
            "modelPolicy": obj.get("modelPolicy"),
            "modelList": obj.get("modelList"),
            "mandatoryGuardrailPreset": obj.get("mandatoryGuardrailPreset"),
            "mandatoryFilterPolicies": obj.get("mandatoryFilterPolicies"),
            "spendLimits": GetGovernanceConfig200ResponseSpendLimits.from_dict(obj["spendLimits"]) if obj.get("spendLimits") is not None else None,
            "version": obj.get("version")
        })
        return _obj


