# coding: utf-8

"""
    QuantCDN API

    Unified API for QuantCDN Admin and QuantCloud Platform services

    The version of the OpenAPI document: 4.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from quantcdn.models.v2_crawler_assets import V2CrawlerAssets
from quantcdn.models.v2_crawler_sitemap_inner import V2CrawlerSitemapInner
from typing import Optional, Set
from typing_extensions import Self

class V2Crawler(BaseModel):
    """
    V2Crawler
    """ # noqa: E501
    id: StrictInt = Field(description="Crawler ID")
    name: Optional[StrictStr] = Field(default=None, description="Crawler name")
    project_id: StrictInt = Field(description="Project ID")
    uuid: StrictStr = Field(description="Crawler UUID")
    config: StrictStr = Field(description="Crawler configuration (YAML)")
    domain: StrictStr = Field(description="Crawler domain")
    domain_verified: Optional[StrictInt] = Field(default=0, description="Domain verification status")
    urls_list: Optional[StrictStr] = Field(default=None, description="URLs list (YAML)")
    webhook_url: Optional[StrictStr] = Field(default=None, description="Webhook URL for notifications")
    webhook_auth_header: Optional[StrictStr] = Field(default=None, description="Authorization header for webhook")
    webhook_extra_vars: Optional[StrictStr] = Field(default=None, description="Extra variables for webhook")
    browser_mode: Optional[StrictBool] = Field(default=None, description="Browser mode enabled")
    workers: Optional[StrictInt] = Field(default=None, description="Number of concurrent workers")
    delay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Delay between requests in seconds")
    depth: Optional[StrictInt] = Field(default=None, description="Maximum crawl depth")
    max_hits: Optional[StrictInt] = Field(default=None, description="Maximum total requests")
    max_html: Optional[StrictInt] = Field(default=None, description="Maximum HTML pages")
    status_ok: Optional[List[StrictInt]] = Field(default=None, description="HTTP status codes for content capture")
    user_agent: Optional[StrictStr] = Field(default=None, description="Custom user agent")
    max_errors: Optional[StrictInt] = Field(default=None, description="Maximum errors before stopping")
    start_urls: Optional[List[StrictStr]] = Field(default=None, description="Starting URLs")
    urls: Optional[List[StrictStr]] = Field(default=None, description="URLs list")
    headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Custom headers")
    exclude: Optional[List[StrictStr]] = Field(default=None, description="URL patterns to exclude")
    include: Optional[List[StrictStr]] = Field(default=None, description="URL patterns to include")
    sitemap: Optional[List[V2CrawlerSitemapInner]] = Field(default=None, description="Sitemap configuration")
    allowed_domains: Optional[List[StrictStr]] = Field(default=None, description="Allowed domains")
    assets: Optional[V2CrawlerAssets] = None
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Deletion timestamp")
    __properties: ClassVar[List[str]] = ["id", "name", "project_id", "uuid", "config", "domain", "domain_verified", "urls_list", "webhook_url", "webhook_auth_header", "webhook_extra_vars", "browser_mode", "workers", "delay", "depth", "max_hits", "max_html", "status_ok", "user_agent", "max_errors", "start_urls", "urls", "headers", "exclude", "include", "sitemap", "allowed_domains", "assets", "created_at", "updated_at", "deleted_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V2Crawler from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sitemap (list)
        _items = []
        if self.sitemap:
            for _item_sitemap in self.sitemap:
                if _item_sitemap:
                    _items.append(_item_sitemap.to_dict())
            _dict['sitemap'] = _items
        # override the default output from pydantic by calling `to_dict()` of assets
        if self.assets:
            _dict['assets'] = self.assets.to_dict()
        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V2Crawler from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "project_id": obj.get("project_id"),
            "uuid": obj.get("uuid"),
            "config": obj.get("config"),
            "domain": obj.get("domain"),
            "domain_verified": obj.get("domain_verified") if obj.get("domain_verified") is not None else 0,
            "urls_list": obj.get("urls_list"),
            "webhook_url": obj.get("webhook_url"),
            "webhook_auth_header": obj.get("webhook_auth_header"),
            "webhook_extra_vars": obj.get("webhook_extra_vars"),
            "browser_mode": obj.get("browser_mode"),
            "workers": obj.get("workers"),
            "delay": obj.get("delay"),
            "depth": obj.get("depth"),
            "max_hits": obj.get("max_hits"),
            "max_html": obj.get("max_html"),
            "status_ok": obj.get("status_ok"),
            "user_agent": obj.get("user_agent"),
            "max_errors": obj.get("max_errors"),
            "start_urls": obj.get("start_urls"),
            "urls": obj.get("urls"),
            "headers": obj.get("headers"),
            "exclude": obj.get("exclude"),
            "include": obj.get("include"),
            "sitemap": [V2CrawlerSitemapInner.from_dict(_item) for _item in obj["sitemap"]] if obj.get("sitemap") is not None else None,
            "allowed_domains": obj.get("allowed_domains"),
            "assets": V2CrawlerAssets.from_dict(obj["assets"]) if obj.get("assets") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at")
        })
        return _obj


